nav:
    - NHN Cloud:
        - "개요": TOAST/ko/Overview.md
        - "사용 가이드": TOAST/ko/user-guide.md
        - "콘솔 사용 가이드": TOAST/ko/console-guide.md
        - "리소스 제공 정책": TOAST/ko/resource-policy.md
        - "보안 정책": TOAST/ko/security-policy.md
site_name: 사용자가이드
theme: readthedocs
